### ISSUE TITLE
Processing IMDB Data Error

### ISSUE THREAD

**Issue by nruggeri19** [RileyXX/IMDB-Trakt-Syncer#101]
### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Bug Description

Successfully signed in to IMDB
Processing Trakt Data
Processing Trakt Data Complete
Processing IMDB Data

--- ERROR ---
An error occurred while running the script.
Please submit the error to GitHub with the following information:
--------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/IMDBTraktSyncer/IMDBTraktSyncer.py", line 128, in main
    imdb_watchlist, imdb_ratings, imdb_reviews, errors_found_getting_imdb_reviews = imdbData.getImdbData(imdb_username, imdb_password, driver, directory, wait)
                                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/IMDBTraktSyncer/imdbData.py", line 135, in getImdbData
    raise ValueError(f"Required columns missing from CSV file: {', '.join(missing_columns)}")
ValueError: Required columns missing from CSV file: Created

### Environment

OS: Mac 
Pip method

**Comment by RileyXX** [comment]
> File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/IMDBTraktSyncer/imdbData.py", line 135, in getImdbData
raise ValueError(f"Required columns missing from CSV file: {', '.join(missing_columns)}")
ValueError: Required columns missing from CSV file: Created

Looks like the CSV watchlist file the script is trying to read is not in the correct format.

When you run the script copy the path to the folder where IMDBTraktSyncer is installed. Go to that folder in file explorer and see if there are any existing .csv files there and delete them. Then try running the script again. This might be causing by running the script multiple times in parallel or the script terminating prematurely during CSV cleanup. The script might be trying to load the ratings csv file instead of the watchlist csv file for example. It's important to only have the script running as one instance. If this was the issue in your case, I can look into adding a check before running to cleanup any old CSV files if they exist to prevent issues like this.

If there are no CSV files in the folder let me know and I can look into this further. You can help troubleshoot by going to your IMDB exports page here https://www.imdb.com/exports/ and downloading your most recent watchlist and ratings files and attach them here.
