### ISSUE TITLE
Unable to restart initial setup if incorrect input given

### ISSUE THREAD

**Issue by MrCredible** [RileyXX/IMDB-Trakt-Syncer#87]
I created this before I read the troubleshooting section of the github page.

I would suggest mentioning "deletion of credentials file if information is input incorrectly" when the syncer is first kicked off before asking for the initial trakt client ID.

But delete this issue, if its not needed.

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Bug Description

When installing via pip and running via cmd, if you input an incorrect value for one of the user inputs, you are unable to correct your previous input.

For example, if you provide the incorrect Trakt ID and push enter and realize after the fact that it was wrong, then you would most likely restart IMDBTraktSyncer. When you restart the syncer, it takes you back to where you left off.

Then if you decide to just give garbage inputs to quickly run through all the required user inputs, it will throw an exception once you reach the request for the URL authorization code. Once you restart, after the exception, it requests the same URL authorization code.

Uninstalling and reinstall does not allow you to start over.

### Environment

windows 11
pip install
ran via cmd

**Comment by RileyXX** [comment]
Thanks very much for your feedback! I will be addressing this in an upcoming patch. 

This problem came up for me a few times as well when I needed to check some things. Due to python limitations uninstalling the project won't remove any files that were created/modified by the script after installation which would be the `credentials.txt` and error `log.txt` files. When uninstalling a python project, python will actually prompt the user with the path(s) to any files that will not be deleted. This is one way you can quickly get the folder path. 

In a future patch the script will print out the folder location where the project is installed every time the script runs. This should make it easier to quickly access the `credentials.txt` and error `log.txt` files.

**Comment by RileyXX** [comment]
For anyone else who comes across this issue, as pointed out by the original poster the solution for invalid credentials can be found in the [troubleshooting section](https://github.com/RileyXX/IMDB-Trakt-Syncer?tab=readme-ov-file#troubleshooting-known-issues-workarounds--future-outlook:~:text=If%20any%20of%20your%20details%20change%20(passwords%2C%20logins%2C%20API%20keys%2C%20etc.)%2C%20simply%20open%20credentials.txt%2C%20modify%20your%20details%2C%20save%20it%20and%20then%20run%20the%20script%20again.%20Alternatively%2C%20delete%20credentials.txt%20to%20reset%20the%20script%20and%20it%20will%20prompt%20you%20to%20enter%20your%20new%20details%20on%20the%20next%20run.) on the main github page: 

> If any of your details change (passwords, logins, API keys, etc.), simply open `credentials.txt`, modify your details, save it and then run the script again. Alternatively, delete `credentials.txt` to reset the script and it will prompt you to enter your new details on the next run.
