### ISSUE TITLE
Setting IMDB Watchlist Items not working properly

### ISSUE THREAD

**Issue by AmineDjeghri** [RileyXX/IMDB-Trakt-Syncer#92]
### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Bug Description

Even if the movies are already present in IMDB watchlist, the script adds them again.

### Environment

WSL (Ubuntu 22)

**Comment by RileyXX** [comment]
This may have been caused by a change in the IMDB CSV export data as mentioned in https://github.com/RileyXX/IMDB-Trakt-Syncer/issues/93. There is a new patch available now ([v1.9.1](https://github.com/RileyXX/IMDB-Trakt-Syncer/releases/tag/v1.9.1)) which should fix this problem.

Try updating to the latest version ([v1.9.1](https://github.com/RileyXX/IMDB-Trakt-Syncer/releases/tag/v1.9.1)) using `python -m pip install IMDBTraktSyncer --upgrade` and let me know whether or not it fixes this problem for you. Thanks!
