### ISSUE TITLE
Possible IMDB captcha check or IMDB login incorrect.

### ISSUE THREAD

**Issue by 1Bl4ck1** [RileyXX/IMDB-Trakt-Syncer#96]
### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Bug Description

Hy, i already posted about this same error in 12.2023 but tried again and again and nothing works. I posted SS. I tried with firefox and chrome. Also made each of them default browser so it isn't that but can't get it to work. I also tried after i needed windows reinstall and still nothing.  I used username from ss i posted and my password with which i log in to imdb. 

### Environment

OS: Windows 11, also tried on Windows 10

### Screenshots

![firefox_xOCxXa5cTc](https://github.com/RileyXX/IMDB-Trakt-Syncer/assets/152782113/5d8615a0-0c08-4ee2-b995-e71aa8b4546f)
![py_tzF2NgeRLv](https://github.com/RileyXX/IMDB-Trakt-Syncer/assets/152782113/423fd92c-8a2b-470c-bb2d-bb8c7e0b1c0a)

**Comment by RileyXX** [comment]
Username should be your email or phone number for logging into IMDB. 

When you get this error you should log out/login on browser as many times as necessary until you trigger captcha check and then complete it. You may need to do this several times until the captcha check is gone. You can also try changing IP address with VPN or something. Otherwise only other thing you can do is wait a few hours/days and try again.

**Comment by 1Bl4ck1** [comment]
Yap, it work i put my e-mail as username. I think it would be good if you updated description and put that needs to be your email or phone number and also log out/login on browser as many times as necessary until you trigger captcha. Just a friendly suggestion

All worked fine! Thank you for making this script! ❤️
